services:
  vca-onvif:
    build: .
    container_name: vca-onvif
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
      CLIP_SECONDS: "${CLIP_SECONDS:-10}"
      COOLDOWN_SECONDS: "${COOLDOWN_SECONDS:-20}"
      DEBUG: "${DEBUG}"
      CAP_TEST: "${CAP_TEST}"

    volumes:
      - ./app/config.yaml:/app/config.yaml:ro
    network_mode: host